# Common vars
availability_zone: melbourne-qh2-uom
instance_image: 45225edb-66d8-4fd0-bf41-132a31a18166
instance_key_name: id_csingh
instance_flavor: uom.general.2c8g
project_working_directory: /home/csingh/unimelb-comp90024-2020-grp-26/
proxy_address: http://wwwproxy.unimelb.edu.au:8000/

# Volumes
volumes:
  - vol_name: volume1
    vol_size: 70
    # device: /dev/vdb
    # mountpoint: /data
  - vol_name: volume2
    vol_size: 20
    # device: /dev/vdb
    # mountpoint: /data
  - vol_name: volume3
    vol_size: 80
    # device: /dev/vdb
    # mountpoint: /data
  - vol_name: volume4
    vol_size: 80
    # device: /dev/vdb
    # mountpoint: /data

# Security groups
security_groups:
  - name: security-group1
    description: "Security group for web server"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: security-group2
    description: "Security group for analysis server"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: security-group3
    description: "Security group for couchdb servers"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0

# Instances
instances:
  - name: web-server
    security_groups: security-group1
    volumes: ['volume1']
  - name: analysis-server
    security_groups: security-group2
    volumes: ['volume2']
  - name: db-servers
    security_groups: security-group3
    volumes: ['volume3', 'volume4']
