- hosts: localhost
  vars_files:
    - variables/vars.yml
  gather_facts: true
  roles:
    - role: common
    - role: show-images
    - role: create-volumes
    - role: create-security-groups
    - role: create-instances