# Team 26
# Hina Bagai - 1070601
# Charu Smita Singh - 1029083
# Ariel Kark - 521428
# Raksha Kammandore Ravi - 1094298

- hosts: localhost
  vars_files:
    - variables/vars.yml
  gather_facts: true
  roles:
    - role: common
    - role: show-images
    - role: create-volumes
    - role: create-security-groups
    - role: create-instances
