- hosts: web-server
  vars_files:
    - variables/vars.yml
  gather_facts: true
  roles:
    - role: common
    - role: show-images
    - role: create-volumes
    - role: create-security-groups
    - role: create-instances
    - role: create-volume-snapshot

# - hosts: db-servers
#   gather_facts: true
#   roles:
#     - role: setup-couchdb
